// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240726095854_holysheet")]
    partial class holysheet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Model.AppFile", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FileID"));

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("FileName_Actual")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FileName_Stored")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<int>("FileTo")
                        .HasColumnType("int");

                    b.Property<byte>("FileType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.HasKey("FileID");

                    b.ToTable("AppFiles");
                });

            modelBuilder.Entity("WebApplication1.Model.LibCountry", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("ISO")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ISO3")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumCode")
                        .HasColumnType("int");

                    b.Property<string>("PrintableName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CountryID");

                    b.ToTable("LibCountries");
                });

            modelBuilder.Entity("WebApplication1.Model.Space", b =>
                {
                    b.Property<int>("SpaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpaceID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateToCancel")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("SpaceDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SpaceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StripeRef")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("SpaceID");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("WebApplication1.Model.SpaceMember", b =>
                {
                    b.Property<int>("SpaceMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpaceMemberID"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InviteID_FK")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SpaceID_FK")
                        .HasColumnType("int");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.Property<byte>("UserRole")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("SpaceMemberID");

                    b.ToTable("SpaceMembers");
                });

            modelBuilder.Entity("WebApplication1.Model.Suite", b =>
                {
                    b.Property<int>("SuiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SuiteID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SpaceID_FK")
                        .HasColumnType("int");

                    b.Property<string>("SuiteDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SuiteName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("SuiteID");

                    b.ToTable("Suites");
                });

            modelBuilder.Entity("WebApplication1.Model.SuiteMember", b =>
                {
                    b.Property<int>("SuiteMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SuiteMemberID"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InviteID_FK")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SuiteID_FK")
                        .HasColumnType("int");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.Property<byte>("UserRole")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("SuiteMemberID");

                    b.ToTable("SuiteMembers");
                });

            modelBuilder.Entity("WebApplication1.Model.SuiteRoom", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasTimeline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoomDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("RoomGroupID_FK")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("RoomPriority")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("RoomStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SuiteID_FK")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.ToTable("SuiteRooms");
                });

            modelBuilder.Entity("WebApplication1.Model.SuiteRoomStage", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StageID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoomID_FK")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<byte>("StagePosition")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("StageID");

                    b.ToTable("SuiteRoomStages");
                });

            modelBuilder.Entity("WebApplication1.Model.SuiteRoomUser", b =>
                {
                    b.Property<int>("RoomUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomUserID"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InviteID_FK")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoomID_FK")
                        .HasColumnType("int");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.Property<byte>("UserRole")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("RoomUserID");

                    b.ToTable("SuiteRoomUsers");
                });

            modelBuilder.Entity("WebApplication1.Model.SuiteTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasTimeline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoomID_FK")
                        .HasColumnType("int");

                    b.Property<int>("StageID_FK")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TaskName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("TaskPriority")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("TaskSequence")
                        .HasColumnType("smallint");

                    b.Property<byte>("TaskStatus")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("TaskID");

                    b.ToTable("SuiteTasks");
                });

            modelBuilder.Entity("WebApplication1.Model.SuiteTaskUser", b =>
                {
                    b.Property<int>("TaskUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskUserID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TaskID_FK")
                        .HasColumnType("int");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.Property<byte>("UserRole")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("TaskUserID");

                    b.ToTable("SuiteTaskUsers");
                });

            modelBuilder.Entity("WebApplication1.Model.TaskChatMessage", b =>
                {
                    b.Property<int>("ChatMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChatMessageID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("TaskID_FK")
                        .HasColumnType("int");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.HasKey("ChatMessageID");

                    b.ToTable("TaskChatMessages");
                });

            modelBuilder.Entity("WebApplication1.Model.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<short>("AccountTimeZone")
                        .HasColumnType("smallint");

                    b.Property<byte>("AccountType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StripeRef")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("WebApplication1.Model.UserLoginDetails", b =>
                {
                    b.Property<int>("UserLoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserLoginID"));

                    b.Property<int>("FailAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LoginPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.HasKey("UserLoginID");

                    b.ToTable("UserLoginDetails");
                });

            modelBuilder.Entity("WebApplication1.Model.UserLoginHistory", b =>
                {
                    b.Property<int>("UserLoginHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserLoginHistoryID"));

                    b.Property<string>("AccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Message")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID_FK")
                        .HasColumnType("int");

                    b.Property<int>("UserLoginID_FK")
                        .HasColumnType("int");

                    b.HasKey("UserLoginHistoryID");

                    b.ToTable("UserLoginHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
